# whole simulation config
- simulation1:
    consensus_name: Strongchain
    miners:
      honest:
        mining_power: 75
      selfish:
        - mining_power: 25
    gamma: 0.5
    weak_to_strong_header_ratio: 10
    simulation_mining_rounds: 1000
