# whole simulation config
- simulation1:
    consensus_name: Nakamoto
    miners:
      honest:
        mining_power: 75
      selfish:
        - mining_power: 25
    gamma: 0.5
    simulation_mining_rounds: 100_000

#- simulation2:
#    example1: Nakamoto_2
#    example_list:
#      - item2_1
#      - item2_2
#      - item3_3
