# whole simulation config
- simulation1:
    example1: Nakamoto
    example_list:
      - item1
      - item2
      - item3

# whole simulation config
- simulation2:
    example1: Nakamoto_2
    example_list:
      - item2_1
      - item2_2
      - item3_3
