# whole simulation config
- simulation1:
    consensus_name: Nakamoto
    miners:
      honest:
        mining_power: 60
      selfish:
        - mining_power: 40
    gamma: 1

## whole simulation config
#- simulation2:
#    example1: Nakamoto_2
#    example_list:
#      - item2_1
#      - item2_2
#      - item3_3
