# whole simulation config
- simulation1:
    consensus_name: Subchain
    miners:
      honest:
        mining_power: 72.5
      selfish:
        - mining_power: 27.5
    gamma: 0.5
    weak_to_strong_block_ratio: 4
    simulation_mining_rounds: 200_000
